### ISSUE TITLE
适配至新版本

### ISSUE THREAD

**Issue by haiman233** [ItsFlicker/SlimefunItemExpansion#7]
适配支持最新粘液科技awa

**Comment by ItsFlicker** [comment]
ok

**Comment by ItsFlicker** [comment]
![image](https://user-images.githubusercontent.com/34670283/159624210-9bbe9842-bea4-476a-9f60-5d5fdd08ce3e.png)

**Comment by ItsFlicker** [comment]
https://github.com/FlickerProjects/SlimefunItemExpansion/releases/tag/latest

**Comment by haiman233** [comment]
\(^o^)/~
